
spring:

  datasource:
    url: jdbc:h2:mem:~/test
    username: teste
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    propertie.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2